<?php
/* Motor CRUD compartido: cada módulo declara tabla, listado y campos editables. */
require_once __DIR__ . '/../config/database.php'; require_once __DIR__ . '/../config/config.php'; checkSession();
$active=['activo'=>'Activo','inactivo'=>'Inactivo'];
$selectPatient="SELECT p.id_paciente id,CONCAT(u.nombre,' ',u.apellido,' — Cédula: ',u.cedula) label FROM pacientes p JOIN usuarios u ON u.id_usuario=p.id_usuario";
$selectDoctor="SELECT d.id_doctor id,CONCAT(u.nombre,' ',u.apellido) label FROM doctores d JOIN usuarios u ON u.id_usuario=d.id_usuario";
$modules=[
'usuarios'=>['t'=>'Usuarios','p'=>'usuarios','table'=>'usuarios','pk'=>'id_usuario','q'=>"SELECT u.id_usuario ID,CONCAT(u.nombre,' ',u.apellido) Nombre,u.usuario_login Usuario,u.email Correo,r.nombre_rol Rol,u.estado Estado FROM usuarios u JOIN roles r ON r.id_rol=u.id_rol ORDER BY u.nombre",'f'=>['id_rol'=>['Rol','select',"SELECT id_rol id,nombre_rol label FROM roles WHERE estado='activo'",1],'nombre'=>['Nombre','text',null,1],'apellido'=>['Apellido','text',null,1],'email'=>['Correo','email',null,1],'telefono'=>['Teléfono'],'usuario_login'=>['Usuario','text',null,1],'contraseña'=>['Contraseña','password',null,0,'password'],'cedula'=>['Cédula','text',null,1],'estado'=>['Estado','select',$active,1]]],
'pacientes'=>['t'=>'Pacientes','p'=>'pacientes','table'=>'pacientes','pk'=>'id_paciente','q'=>"SELECT p.id_paciente ID,CONCAT(u.nombre,' ',u.apellido) Nombre,u.email Correo,u.telefono Teléfono,p.tipo_sangre AS 'Tipo sangre',p.ciudad Ciudad,p.estado Estado FROM pacientes p JOIN usuarios u ON u.id_usuario=p.id_usuario ORDER BY u.nombre",'f'=>['id_usuario'=>['Usuario paciente','select',"SELECT u.id_usuario id,CONCAT(u.nombre,' ',u.apellido,' — ',u.email) label FROM usuarios u LEFT JOIN pacientes p ON p.id_usuario=u.id_usuario WHERE u.id_rol=4 AND p.id_usuario IS NULL",1],'tipo_sangre'=>['Tipo de sangre'],'alergias'=>['Alergias','textarea'],'enfermedades_cronicas'=>['Enfermedades crónicas','textarea'],'fecha_nacimiento'=>['Fecha de nacimiento','date'],'genero'=>['Género','select',['masculino'=>'Masculino','femenino'=>'Femenino','otro'=>'Otro']],'direccion'=>['Dirección','textarea'],'ciudad'=>['Ciudad'],'codigo_postal'=>['Código postal'],'estado_civil'=>['Estado civil','select',['soltero'=>'Soltero','casado'=>'Casado','divorciado'=>'Divorciado','viudo'=>'Viudo']],'contacto_emergencia'=>['Contacto de emergencia'],'telefono_emergencia'=>['Teléfono de emergencia'],'estado'=>['Estado','select',$active,1]]],
'especialidades'=>['t'=>'Especialidades','p'=>'doctores','table'=>'especialidades','pk'=>'id_especialidad','q'=>"SELECT id_especialidad ID,nombre_especialidad Especialidad,descripcion Descripción,estado Estado FROM especialidades ORDER BY nombre_especialidad",'f'=>['nombre_especialidad'=>['Nombre','text',null,1],'descripcion'=>['Descripción','textarea'],'estado'=>['Estado','select',$active,1]]],
'servicios'=>['t'=>'Servicios','p'=>'doctores','table'=>'servicios','pk'=>'id_servicio','q'=>"SELECT id_servicio ID,nombre_servicio Servicio,descripcion Descripción,costo_servicio Costo,duracion_minutos AS 'Duración (min.)',estado Estado FROM servicios ORDER BY nombre_servicio",'f'=>['nombre_servicio'=>['Nombre','text',null,1],'descripcion'=>['Descripción','textarea'],'costo_servicio'=>['Costo','number',null,1,'step=0.01'],'duracion_minutos'=>['Duración (minutos)','number'],'estado'=>['Estado','select',$active,1]]],
'doctores'=>['t'=>'Doctores','p'=>'doctores','table'=>'doctores','pk'=>'id_doctor','q'=>"SELECT d.id_doctor ID,CONCAT(u.nombre,' ',u.apellido) Nombre,e.nombre_especialidad Especialidad,d.numero_colegiado Colegiado,d.experiencia_años AS 'Experiencia (años)',d.estado Estado FROM doctores d JOIN usuarios u ON u.id_usuario=d.id_usuario JOIN especialidades e ON e.id_especialidad=d.id_especialidad ORDER BY u.nombre",'f'=>['id_usuario'=>['Usuario doctor','select',"SELECT u.id_usuario id,CONCAT(u.nombre,' ',u.apellido,' — ',u.email) label FROM usuarios u LEFT JOIN doctores d ON d.id_usuario=u.id_usuario WHERE u.id_rol=2 AND d.id_usuario IS NULL",1],'id_especialidad'=>['Especialidad','select',"SELECT id_especialidad id,nombre_especialidad label FROM especialidades WHERE estado='activo'",1],'numero_colegiado'=>['Número de colegiado','text',null,1],'experiencia_años'=>['Experiencia (años)','number'],'horario_entrada'=>['Hora de entrada','time'],'horario_salida'=>['Hora de salida','time'],'estado'=>['Estado','select',['activo'=>'Activo','inactivo'=>'Inactivo','licencia'=>'Licencia'],1]]],
'citas'=>['t'=>'Citas','p'=>'citas','table'=>'citas','pk'=>'id_cita','q'=>"SELECT c.id_cita ID,c.fecha_cita Fecha,TIME_FORMAT(c.hora_cita,'%H:%i') Hora,CONCAT(pu.nombre,' ',pu.apellido) Paciente,CONCAT(du.nombre,' ',du.apellido) Doctor,s.nombre_servicio Servicio,c.estado_cita Estado FROM citas c JOIN pacientes p ON p.id_paciente=c.id_paciente JOIN usuarios pu ON pu.id_usuario=p.id_usuario JOIN doctores d ON d.id_doctor=c.id_doctor JOIN usuarios du ON du.id_usuario=d.id_usuario JOIN servicios s ON s.id_servicio=c.id_servicio ORDER BY c.fecha_cita DESC,c.hora_cita DESC",'f'=>['id_paciente'=>['Paciente','select',$selectPatient,1],'id_doctor'=>['Doctor','select',$selectDoctor,1],'id_servicio'=>['Servicio','select',"SELECT id_servicio id,nombre_servicio label FROM servicios WHERE estado='activo'",1],'fecha_cita'=>['Fecha','date',null,1],'hora_cita'=>['Hora','time',null,1],'estado_cita'=>['Estado','select',['programada'=>'Programada','completada'=>'Completada','cancelada'=>'Cancelada','no_asistio'=>'No asistió'],1],'notas'=>['Notas','textarea']]],
'consultas'=>['t'=>'Consultas clínicas','p'=>'consultas','table'=>'consultas','pk'=>'id_consulta','q'=>"SELECT co.id_consulta ID,DATE(co.fecha_consulta) Fecha,CONCAT(pu.nombre,' ',pu.apellido) Paciente,CONCAT(du.nombre,' ',du.apellido) Doctor,co.diagnostico Diagnóstico,co.estado_consulta Estado FROM consultas co JOIN pacientes p ON p.id_paciente=co.id_paciente JOIN usuarios pu ON pu.id_usuario=p.id_usuario JOIN doctores d ON d.id_doctor=co.id_doctor JOIN usuarios du ON du.id_usuario=d.id_usuario ORDER BY co.fecha_consulta DESC",'f'=>['id_cita'=>['Cita','select',"SELECT c.id_cita id,CONCAT(c.fecha_cita,' ',TIME_FORMAT(c.hora_cita,'%H:%i'),' — ',u.nombre,' ',u.apellido) label FROM citas c JOIN pacientes p ON p.id_paciente=c.id_paciente JOIN usuarios u ON u.id_usuario=p.id_usuario",1],'id_paciente'=>['Paciente','select',$selectPatient,1],'id_doctor'=>['Doctor','select',$selectDoctor,1],'motivo_consulta'=>['Motivo','textarea',null,1],'diagnostico'=>['Diagnóstico','textarea',null,1],'tratamiento'=>['Tratamiento','textarea'],'medicamentos_prescritos'=>['Medicamentos','textarea'],'observaciones'=>['Observaciones','textarea'],'proxima_cita'=>['Próxima cita','date'],'estado_consulta'=>['Estado','select',['completada'=>'Completada','pendiente'=>'Pendiente','cancelada'=>'Cancelada'],1]]],
'facturacion'=>['t'=>'Facturación','p'=>'facturacion','table'=>'facturacion','pk'=>'id_factura','q'=>"SELECT f.id_factura ID,f.numero_factura Factura,f.fecha_factura Fecha,CONCAT(u.nombre,' ',u.apellido) Paciente,f.total Total,f.metodo_pago Método,f.estado_factura Estado FROM facturacion f JOIN pacientes p ON p.id_paciente=f.id_paciente JOIN usuarios u ON u.id_usuario=p.id_usuario ORDER BY f.fecha_factura DESC",'f'=>['id_paciente'=>['Paciente','select',$selectPatient,1],'id_consulta'=>['Consulta (opcional)','select',"SELECT id_consulta id,CONCAT('Consulta #',id_consulta) label FROM consultas"],'numero_factura'=>['Número de factura','text',null,1,'default=FAC-'.date('Ymd-His')],'fecha_factura'=>['Fecha','date',null,1,'default='.date('Y-m-d')],'descripcion_servicios'=>['Descripción','textarea',null,1],'subtotal'=>['Subtotal','number',null,1,'step=0.01'],'impuesto'=>['Impuesto','number',null,0,'step=0.01 default=0'],'total'=>['Total','number',null,1,'step=0.01'],'metodo_pago'=>['Método','select',['efectivo'=>'Efectivo','tarjeta'=>'Tarjeta','transferencia'=>'Transferencia','cheque'=>'Cheque'],1],'estado_factura'=>['Estado','select',['pagada'=>'Pagada','pendiente'=>'Pendiente','anulada'=>'Anulada'],1],'notas'=>['Notas','textarea']]],
'inventario'=>['t'=>'Inventario','p'=>'inventario','table'=>'inventario','pk'=>'id_inventario','q'=>"SELECT id_inventario ID,nombre_producto Producto,cantidad Existencias,cantidad_minima Mínimo,precio_unitario AS 'Precio unitario',fecha_vencimiento Vencimiento,proveedor Proveedor,estado Estado FROM inventario ORDER BY nombre_producto",'f'=>['nombre_producto'=>['Producto','text',null,1],'descripcion'=>['Descripción','textarea'],'cantidad'=>['Existencias','number',null,1],'cantidad_minima'=>['Cantidad mínima','number'],'precio_unitario'=>['Precio unitario','number',null,1,'step=0.01'],'fecha_vencimiento'=>['Vencimiento','date'],'proveedor'=>['Proveedor'],'estado'=>['Estado','select',$active,1]]],
'pagos'=>['t'=>'Pagos','p'=>'historial_facturacion','table'=>'historial_facturacion','pk'=>'id_historial_factura','q'=>"SELECT hf.id_historial_factura ID,f.numero_factura Factura,hf.fecha_pago Fecha,hf.monto_pago Monto,hf.metodo_pago Método,hf.referencia_pago Referencia,hf.estado_pago Estado FROM historial_facturacion hf JOIN facturacion f ON f.id_factura=hf.id_factura ORDER BY hf.fecha_pago DESC",'f'=>['id_factura'=>['Factura','select',"SELECT id_factura id,numero_factura label FROM facturacion WHERE estado_factura<>'anulada'",1],'id_paciente'=>['Paciente','select',$selectPatient,1],'monto_pago'=>['Monto','number',null,1,'step=0.01'],'fecha_pago'=>['Fecha','date',null,1,'default='.date('Y-m-d')],'hora_pago'=>['Hora','time'],'metodo_pago'=>['Método','select',['efectivo'=>'Efectivo','tarjeta'=>'Tarjeta','transferencia'=>'Transferencia','cheque'=>'Cheque'],1],'referencia_pago'=>['Referencia'],'estado_pago'=>['Estado','select',['confirmado'=>'Confirmado','pendiente'=>'Pendiente','rechazado'=>'Rechazado'],1],'notas'=>['Notas','textarea']]],
'historial'=>['t'=>'Historial clínico','p'=>'historial_paciente','table'=>'historial_paciente','pk'=>'id_historial','q'=>"SELECT h.id_historial ID,h.fecha_evento Fecha,CONCAT(pu.nombre,' ',pu.apellido) Paciente,CONCAT(du.nombre,' ',du.apellido) Doctor,h.tipo_evento Evento,h.descripcion_evento Descripción FROM historial_paciente h JOIN pacientes p ON p.id_paciente=h.id_paciente JOIN usuarios pu ON pu.id_usuario=p.id_usuario JOIN doctores d ON d.id_doctor=h.id_doctor JOIN usuarios du ON du.id_usuario=d.id_usuario ORDER BY h.fecha_evento DESC",'f'=>['id_paciente'=>['Paciente','select',$selectPatient,1],'id_doctor'=>['Doctor','select',$selectDoctor,1],'tipo_evento'=>['Tipo de evento'],'descripcion_evento'=>['Descripción','textarea',null,1],'datos_clinicos'=>['Datos clínicos','textarea'],'fecha_proxima_revision'=>['Próxima revisión','date']]],
];
// La base V2 usa identificadores ASCII para la contraseña; el campo visual mantiene su etiqueta.
foreach ($modules['usuarios']['f'] as $key => $field) {
    if (($field[4] ?? '') === 'password') {
        $modules['usuarios']['f']['password_hash'] = $field;
        unset($modules['usuarios']['f'][$key]);
        break;
    }
}
$modules['usuarios']['f']['password_hash'][3] = 1;

// Recepción puede crear cuentas de pacientes, pero no modificar ni eliminar cuentas existentes.
if (($_SESSION['user_role'] ?? null) == ROLE_RECEPCIONISTA && ($module ?? '') === 'usuarios') {
    $modules['usuarios']['f']['id_rol'][2] = ['4' => 'Paciente'];
    if (isset($_GET['edit']) || ($_SERVER['REQUEST_METHOD'] === 'POST' && (($_POST['action'] ?? '') === 'delete' || !empty($_POST['id'])))) {
        http_response_code(403);
        exit('La Recepcionista solo puede crear usuarios pacientes.');
    }
}
// Compatibilidad con nombres ASCII del esquema V2.
$modules['doctores']['q'] = str_replace('experiencia_años', 'experiencia_anios', $modules['doctores']['q']);
foreach ($modules['doctores']['f'] as $key => $field) {
    if (strpos($key, 'experiencia') === 0) {
        $modules['doctores']['f']['experiencia_anios'] = $field;
        unset($modules['doctores']['f'][$key]);
        break;
    }
}
if(!isset($module,$modules[$module])){http_response_code(404);exit('Módulo no encontrado.');}$m=$modules[$module];if(!checkPermission($m['p'])&&$_SESSION['user_role']!=ROLE_ADMIN){header('Location: '.BASE_URL.'/index.php');exit();}
// En el alta de citas, Recepción puede limitar el listado de pacientes por nombre o cédula.
$appointmentPatientSearch = trim($_GET['buscar_paciente'] ?? '');
if ($module === 'citas' && $_SESSION['user_role'] == ROLE_RECEPCIONISTA && $appointmentPatientSearch !== '') {
    $like = '%' . $appointmentPatientSearch . '%';
    $m['f']['id_paciente'][2] = [
        'sql' => "SELECT p.id_paciente id, CONCAT(u.nombre, ' ', u.apellido, ' — Cédula: ', u.cedula) label FROM pacientes p JOIN usuarios u ON u.id_usuario = p.id_usuario WHERE CONCAT(u.nombre, ' ', u.apellido) LIKE ? OR u.cedula LIKE ? ORDER BY u.nombre, u.apellido",
        'params' => [$like, $like]
    ];
}
// Recepción puede localizar una factura por número, paciente o cédula sin recorrer todo el listado.
$billingSearch = trim($_GET['buscar_factura'] ?? '');
if ($module === 'facturacion' && $_SESSION['user_role'] == ROLE_RECEPCIONISTA && $billingSearch !== '') {
    $like = '%' . $billingSearch . '%';
    $m['q'] = "SELECT f.id_factura ID, f.numero_factura Factura, f.fecha_factura Fecha, CONCAT(u.nombre, ' ', u.apellido) Paciente, f.total Total, f.metodo_pago Método, f.estado_factura Estado FROM facturacion f JOIN pacientes p ON p.id_paciente = f.id_paciente JOIN usuarios u ON u.id_usuario = p.id_usuario WHERE f.numero_factura LIKE ? OR CONCAT(u.nombre, ' ', u.apellido) LIKE ? OR u.cedula LIKE ? ORDER BY f.fecha_factura DESC";
    $m['list_params'] = [$like, $like, $like];
}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));$message='';$error='';
// Devuelve las opciones de un campo desplegable, ya sea desde SQL o desde una lista simple.
function choices($f){if(is_string($f[2]??null))return getRecords($f[2]);if(is_array($f[2]??null)&&isset($f[2]['sql']))return getRecords($f[2]['sql'],$f[2]['params']??[]);$result=[];foreach(($f[2]??[]) as $id=>$label)$result[]=['id'=>$id,'label'=>$label];return $result;}
if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['csrf'],$_POST['csrf']??''))$error='La solicitud expiró. Vuelva a intentarlo.';else try{if(($_POST['action']??'')==='delete'){executeQuery("DELETE FROM {$m['table']} WHERE {$m['pk']}=?",[(int)$_POST['id']]);$message='Registro eliminado.';}elseif(($_POST['action']??'')==='save'){$data=[];foreach($m['f'] as $name=>$f){$value=trim((string)($_POST[$name]??''));$password=($f[4]??'')==='password';if($password&&$value==='')continue;$required=!empty($f[3]);if($value===''&&$required)throw new Exception('Complete los campos obligatorios.');if($value==='')$value=null;if($password)$value=hashPassword($value);$data[$name]=$value;}if(!empty($_POST['id'])){if(!updateRecord($m['table'],$data,$m['pk'],(int)$_POST['id']))throw new Exception('Error al actualizar');$message='Registro actualizado.';}else{if(!insertRecord($m['table'],$data))throw new Exception('Error al crear');$message='Registro creado.';}}}catch(Throwable $e){error_log($e->getMessage());$error='No fue posible guardar. Revise campos duplicados y relaciones requeridas.';}}
$current=null;if(isset($_GET['edit']))$current=getRecord("SELECT * FROM {$m['table']} WHERE {$m['pk']}=?",[(int)$_GET['edit']]);$show=isset($_GET['new'])||$current;$rows=getRecords($m['q'],$m['list_params']??[]);include __DIR__.'/header.php';
?>
<div class="page-header"><div><h1><?=htmlspecialchars($m['t'])?></h1><p>Gestión de registros.</p></div><a class="btn btn-primary" href="?new=1">Nuevo registro</a></div><?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message)?></div><?php endif;if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<?php if($show):?><section class="content-section form-panel"><h2><?=$current?'Editar registro':'Nuevo registro'?></h2><?php if($module==='citas' && $_SESSION['user_role']==ROLE_RECEPCIONISTA):?><form method="get" class="appointment-patient-search"><input type="hidden" name="new" value="1"><label for="buscar_paciente">Buscar paciente por nombre o cédula</label><div><input class="form-control" id="buscar_paciente" type="search" name="buscar_paciente" value="<?=htmlspecialchars($appointmentPatientSearch)?>" placeholder="Buscar por nombre o cédula"><button class="btn btn-secondary">Buscar paciente</button><?php if($appointmentPatientSearch):?><a class="btn btn-secondary" href="?new=1">Limpiar</a><?php endif;?></div></form><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="action" value="save"><?php if($current):?><input type="hidden" name="id" value="<?=(int)$current[$m['pk']]?>"><?php endif;?><div class="form-grid"><?php foreach($m['f'] as $name=>$f):$type=$f[1]??'text';$meta=$f[4]??'';$default=str_contains($meta,'default=')?substr($meta,strpos($meta,'default=')+8):'';$value=$_POST[$name]??($current[$name]??$default);?><div class="form-group"><label><?=$f[0]?><?=!empty($f[3])?' *':''?></label><?php if($type==='textarea'):?><textarea class="form-control" name="<?=$name?>"><?=htmlspecialchars((string)$value)?></textarea><?php elseif($type==='select'):?><select class="form-control" name="<?=$name?>"><option value="">Seleccione…</option><?php foreach(choices($f) as $o):?><option value="<?=htmlspecialchars($o['id'])?>" <?=((string)$value===(string)$o['id'])?'selected':''?>><?=htmlspecialchars($o['label'])?></option><?php endforeach;?></select><?php else:?><input class="form-control" name="<?=$name?>" type="<?=$type?>" <?=str_contains($meta,'step=')?'step="'.substr($meta,strpos($meta,'step=')+5,4).'"':''?> value="<?=htmlspecialchars($type==='password'?'':(string)$value)?>"><?php endif;?></div><?php endforeach;?></div><button class="btn btn-primary">Guardar</button> <a class="btn btn-secondary" href="?">Cancelar</a></form></section><?php endif;?>
<section class="content-section mt-20"><?php if(!$rows):?><div class="alert alert-info">No hay registros para mostrar.</div><?php else:?><div class="table-responsive"><table class="table"><thead><tr><?php foreach(array_keys($rows[0]) as $h):?><th><?=htmlspecialchars($h)?></th><?php endforeach;?><th>Acciones</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><?php foreach($r as $h=>$v):?><td><?php if(strtolower($h)==='estado'):?><span class="badge badge-<?=htmlspecialchars($v)?>"><?php endif;?><?=htmlspecialchars((string)($v??'—'))?><?php if(strtolower($h)==='estado'):?></span><?php endif;?></td><?php endforeach;?><td class="actions"><a class="btn btn-sm btn-primary" href="?edit=<?=(int)$r['ID']?>">Editar</a><form method="post" onsubmit="return confirm('¿Eliminar este registro?');"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$r['ID']?>"><button class="btn btn-sm btn-danger">Eliminar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><style>.page-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;border-bottom:2px solid var(--gray-300);padding-bottom:16px}.content-section{background:#fff;padding:20px;border-radius:8px;box-shadow:var(--box-shadow)}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 20px}.actions{display:flex;gap:8px}.actions form{margin:0}.appointment-patient-search{background:#eef8f0;border:1px solid #b9dfc0;border-radius:8px;padding:14px;margin:0 0 20px}.appointment-patient-search label{display:block;font-weight:600;margin-bottom:8px}.appointment-patient-search>div{display:flex;gap:10px}.appointment-patient-search .form-control{max-width:390px}@media(max-width:650px){.page-header{align-items:flex-start;gap:12px;flex-direction:column}.form-grid{grid-template-columns:1fr}.appointment-patient-search>div{flex-direction:column}.appointment-patient-search .form-control{max-width:none}}</style><?php include __DIR__.'/footer.php';?>
